### ISSUE TITLE
/conf/proxy/roles/live/private-proxy/001_default.yml missing var declaration

### ISSUE THREAD

**Issue by jl-sitnrw** [iris-connect/iris-client#467]
Version: 1.1.0
Standalone
in this config ```/conf/proxy/roles/live/private-proxy/001_default.yml``` file the var IRIS_CLIENT_BFF_ENDPOINT is used
```  
  internal_endpoint:
    address: "$IRIS_CLIENT_BFF_ENDPOINT"
```
 but is not declared in the vars section. If I try to start the proxy without modification of this file, I get the error:
```
start-private-proxy.sh[1097]: time="2021-11-15T09:19:37+01:00" level=error msg="Error loading settings from path 'conf/proxy/roles/live/private-proxy': load settings conf/proxy/roles/live/private-proxy/001_default.yml: undefined variable: 'IRIS_CLIENT_BFF_ENDPOINT'"
```
please add
```  
  IRIS_CLIENT_BFF_ENDPOINT:
    source: env
    variable: IRIS_CLIENT_BFF_ENDPOINT
    type: string
```
in var section upstream.

regards
